added modules vector_ques and hash_map_ques in Feature/assignment 10
ankit-mogha/KUP_Rust pull request #13
Opened 2021-03-16 08:16 UTC by ankit-mogha

What does this change do?
1. hash_map_ques module has hash_map.rs file that has a function sum_conditionals function matches a particular pattern in Key of hashmap.

2. vector_ques has the following modules:- 
   i. add_duplicates.rs:- have a duplicate function that duplicates the elements of the list. 
   ii. first_even_number.rs:- have a  first_even function that checks the first even number in the list.
   iii. list_palindrome.rs:- have an is_palindrome function checks if the list is palindrome or not.
   iv. remove_duplicate.rs:- have a compress function that removes duplicates elements from the list.
   v. remove_nth_element:- have a drop function that finds the given number in the list and removes it.
   vi. reverse_list.rs:- have a reverse function that reverses the list.

Any additional information for the reviewer to start
NA

How should this be manually tested?
We need window OS in which Rust is installed. then execute this rust program

Which Trello task and sub-task does this change relate to?

Are there any changes pending?
No

Does any team have to be notified of changes in this feature?
Yes

Definition of Done:
- [x] Is there >90% unit test code coverage?
if not please mention the Code Coverage of code.
- [x] Does this PR add new dependencies? If so, please list out the same.
      -  log
- [ ]  Will this feature require a new piece of infrastructure to be implemented?
- [x] Is there appropriate logging included?
- [x] Does the project compile ok?
- [x] Have Clippy violations been fixed?
- [x] Have the Code is properly formatted?

2021-03-16 12:03 UTC, aman09v requested changes

2021-03-16 12:03 UTC, aman09v commented on assignments/assignment_ten/src/vector_ques/reverse_list.rs
> +            None => println!("no"),
do not use print statements

2021-03-16 12:28 UTC, ankit-mogha commented on assignments/assignment_ten/src/vector_ques/reverse_list.rs
> +            None => println!("no"),
updated the file

2021-03-16 13:04 UTC, aman09v approved these changes

2021-03-16 17:10 UTC, sonukumar-a11 approved these changes
Use a single function for particular module test

2021-03-16 17:17 UTC, Dheerajjnv approved these changes

2021-03-16 17:22 UTC, NitinSaxenait commented on assignments/assignment_ten/src/vector_ques/add_duplicates.rs
> +    println!("{}", vec.len());
println ?? not needed

2021-03-16 17:23 UTC, NitinSaxenait commented on assignments/assignment_ten/src/vector_ques/add_duplicates.rs
> +    log::info!("List : {:?}", res);
wrong use of info.

2021-03-16 17:25 UTC, NitinSaxenait commented on assignments/assignment_ten/src/vector_ques/remove_duplicate.rs
> +    log::info!("List : {:?}", res);
info use!! not correct.

2021-03-16 17:26 UTC, NitinSaxenait approved these changes

2024-07-19 10:00 UTC, merged

2024-07-19 10:02 UTC, NitinSaxenait commented
Kya kr rhe ho ankit bhai. Damad bna lia kya knoldus ne

On Fri, 19 Jul 2024 at 3:30 PM, Ankit Mogha ***@***.***>
wrote:

> Merged #13 <https://github.com/ankit-mogha/KUP_Rust/pull/13> into main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ankit-mogha/KUP_Rust/pull/13#event-13572011339>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASL5XPLG5OT2G4DQV2TFELLZNDPVHAVCNFSM6AAAAABLEI54L6VHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJTGU3TEMBRGEZTGOI>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>