added module library_structure implementing OOPs concepts
ankit-mogha/KUP_Rust pull request #18
Opened 2021-03-20 06:45 UTC by ankit-mogha

What does this change do?
Implements the oops concepts

Any additional information for the reviewer to start
NA

How should this be manually tested?
We need window OS in which Rust is installed. then execute this rust program

Which Trello task and sub-task does this change relate to?

Are there any changes pending?
No

Does any team have to be notified of changes in this feature?
Yes

Definition of Done:
- [x] Is there >90% unit test code coverage?
if not please mention the Code Coverage of code.
- [x] Does this PR add new dependencies? If so, please list out the same.
      -log  -env_logger
- [ ]  Will this feature require a new piece of infrastructure to be implemented?
- [x] Is there appropriate logging included?
- [x] Does the project compile ok?
- [x] Have Clippy violations been fixed?
- [x] Have the Code is properly formatted?

2021-03-20 06:55 UTC, aman09v requested changes

2021-03-20 06:55 UTC, aman09v commented on assignments/assignment_thirteen/src/library_structure/book_structure.rs
> +    pub fn total_number_of_books(&self, no_books: &[i32]) -> usize {
use proper wrapping for return values

2021-03-20 06:59 UTC, aman09v approved these changes

2021-03-20 11:36 UTC, Dheerajjnv approved these changes

2021-03-22 09:09 UTC, Dheerajjnv commented on assignments/assignment_thirteen/src/library_structure/book_structure.rs
> +            /*Book {
Delete this commented lines.

2021-03-22 09:24 UTC, ankit-mogha commented on assignments/assignment_thirteen/src/library_structure/book_structure.rs
> +            /*Book {
updated

2024-07-19 10:00 UTC, merged